#!/bin/bash

if [ "$(dpkg --print-architecture)" = "arm64" ]; then export VCPKG_FORCE_SYSTEM_BINARIES=1; fi

cmake --preset="unix-game-server-only" -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=1
cmake --build build --config Release
